all: alse6b.exe alse6bcf.exe alse6bdb.exe

dos: alse6b.dos alse6bcf.dos alse6bdb.dos

alse6b.exe: source\alse6b.bas
    basicc alse6b /OS

alse6bcf.exe: source\alse6bcf.bas
    basicc alse6bcf /OS

alse6bdb.exe: source\alse6bdb.bas
    basicc alse6bdb /OS

alse6b.dos: source\alse6b.bas
    basicc alse6b /LC

alse6bcf.dos: source\alse6bcf.bas
    basicc alse6bcf /LC

alse6bdb.dos: source\alse6bdb.bas
    basicc alse6bdb /LC
